#! /bin/sh

nitrogen --restore &
xcompmgr -c &
$HOME/.config/polybar/launch.sh
sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap           3

bspc config size_border        	 1
bspc config size_gap		 5

bspc config padding_top		 0
bspc config padding_bottom	 0
bspc config padding_left	 0
bspc config padding_right	 0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Firefox desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
